### ISSUE TITLE
Bugs my brother from python-forums.io helped me find. 1/1/2023

### ISSUE THREAD

**Issue by metulburr** [robgraves/crapsgame#1]
1. User that is None, bankroll is None
2. Free odds bet with no bank roll, you cant return to game
3. Returning user that doesnt exist returns None

**Comment by metulburr** [comment]
https://python-forum.io/thread-20.html

**Comment by robgraves** [comment]
Sweet, thanks for helping me fish out the bugs.  I wanted you to try to break it and you found the couple spots I missed.  Gonna fix these three issues, then I'm gonna split code into multiple files and directories for ease of traversing the code and some organization, then I plan to start writing the rest of the bets, starting with the field bet and probably the buy and lay bets for each point number (4,5,6,8,9, and 10).

**Comment by robgraves** [comment]
4. Quit from Come-Out roll menu (the oldest part of the game) doesn't call gameover() function thus displaying proper leaving sequence.

**Comment by robgraves** [comment]
I cannot recreate Bug #1, I had thought the issue was the user created's name was just an Enter but now when I do it this unnamed player still gets a bankroll.  Also tried to have a player name with just spaces or special characters and seems to still bankroll the player.

**Comment by robgraves** [comment]
All 4 bugs appear to be fixed now.  Checking for someone else to retest game to see if any of these bugs can be reproduced.
