### ISSUE TITLE
Overwriting existing user if you create new user as duplicate

### ISSUE THREAD

**Issue by metulburr** [robgraves/crapsgame#3]
You overwrite an existing user by selecting new user accidentally and creating the same username

to replicate:

1. Create new user
2. modify cash total and exit
3. select new user
4. enter original username from before
5. overwrites user with default cash instead of stating the user already exists

**Comment by metulburr** [comment]
### string format is your friend

>>> die1 = 11
>>> die2 = 22
'11 22'

**Comment by robgraves** [comment]
> and string format is your friend
> 
> > > > die1 = 11
> > > > die2 = 22
> > > > '{} {}'.format(die1, die2)
> 
> '11 22'
> 
> or the f-string
> 
> > > > die1 = 11
> > > > die2 = 22
> > > > f'{die1} {die2}'
> 
> '11 22'

Is this a reference to Line 99?
    print(str(die1) + " " + str(die2))

Also what is this:
{} {}  
???

I think I"m rejecting this change though because readability is important to me and the way I have it written makes more sense to me than the code examples you just posted.

I will fix the overwriting user, however.

**Comment by robgraves** [comment]
Marking issue as resolved.  New push at 11:06 PM New York time on 01/07/2023 fixes the overwrite of player save data if same name is used.
